import { ProductsRow } from "../../components/app-content/components/app-content-body/components/products-row";

export const Tires = () => {
  const products = [
    {
      id: 1,
      brand_name: "Bridgestone",
      mark: "Potenza",
      width: 195,
      height: 65,
      radius: 15,
      season: "Лето",
      status: 1,
      year: 2023,
      price: 15500,
    },
    {
      id: 2,
      brand_name: "Yokohama",
      mark: "Geolendar",
      width: 215,
      height: 70,
      radius: 16,
      season: "Лето",
      status: 0,
      year: 2023,
      price: 23500,
    },
    {
      id: 3,
      brand_name: "Dunlop",
      mark: "DSX",
      width: 195,
      height: 65,
      radius: 15,
      season: "Зима",
      status: 1,
      year: 2023,
      price: 13500,
    },
    {
      id: 4,
      brand_name: "Bridgestone",
      mark: "Potenza",
      width: 195,
      height: 65,
      radius: 15,
      season: "Лето",
      status: 2,
      year: 2023,
      price: 15500,
    },
    {
      id: 5,
      brand_name: "Yokohama",
      mark: "Geolendar",
      width: 215,
      height: 70,
      radius: 16,
      season: "Лето",
      status: 1,
      year: 2024,
      price: 23500,
    },
    {
      id: 6,
      brand_name: "Dunlop",
      mark: "DSX",
      width: 195,
      height: 65,
      radius: 15,
      season: "Зима",
      status: 1,
      year: 2023,
      price: 13500,
    },
    {
      id: 7,
      brand_name: "Dunlop",
      mark: "DSX",
      width: 195,
      height: 65,
      radius: 15,
      season: "Зима",
      status: 1,
      year: 2023,
      price: 13500,
    },
    {
      id: 8,
      brand_name: "Bridgestone",
      mark: "Potenza",
      width: 195,
      height: 65,
      radius: 15,
      season: "Лето",
      status: 2,
      year: 2023,
      price: 15500,
    },
    {
      id: 9,
      brand_name: "Yokohama",
      mark: "Geolendar",
      width: 215,
      height: 70,
      radius: 16,
      season: "Лето",
      status: 1,
      year: 2024,
      price: 23500,
    },
    {
      id: 10,
      brand_name: "Dunlop",
      mark: "DSX",
      width: 195,
      height: 65,
      radius: 15,
      season: "Зима",
      status: 1,
      year: 2023,
      price: 13500,
    },
  ];
  return (
    <div style={{ display: "flex", flexWrap: "wrap", margin: "0 15px" }}>
      {products.map((product) => {
        return <ProductsRow key={product.id} product={product} />;
      })}
    </div>
  );
};
