export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_POST_DATA: "SET_POST_DATA",
  CLOSE_MODAL: "CLOSE_MODAL",
  OPEN_MODAL: "OPEN_MODAL",
  RESET_POST_DATA: "RESET_POST_DATA",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  CHANGE_CATEGORY: "CHANGE_CATEGORY",
  SET_LOADING: "SET_LOADING",
  LOAD_CATEGORIES: "LOAD_CATEGORIES",
};
