export * from "./main/main";
export * from "./products/products";
export * from "./tires/tires";
export * from "./basket/basket";
export * from "./about/about";
export * from "./authorization/authorization";
export * from "./registration/registration";
export * from "./brands/brands";
export * from "./marks/marks";
